const BLOCK_SIZE = 128;
const BLOCK_COUNT = 992; // (1024 / 8 - 4) * 8
const DEVICE_SIZE = BLOCK_SIZE * BLOCK_COUNT;

const MAX_SYMLINK_DEPTH = 3;

// object size

const ADDRESS_SIZE = 4;

const DENTRY_SIZE = 64;

const INODE_INO_SIZE = 4;
const INODE_TYPE_SIZE = 2;
const INODE_SIZE_SIZE = 4;
const INODE_REFS_SIZE = 2;
const INODE_STRAIGHT_LINKS_COUNT = 11;
const INODE_SIZE = // 64
  INODE_INO_SIZE +
  INODE_TYPE_SIZE +
  INODE_SIZE_SIZE +
  INODE_REFS_SIZE +
  ADDRESS_SIZE * INODE_STRAIGHT_LINKS_COUNT +
  ADDRESS_SIZE +
  ADDRESS_SIZE;
const N_SIZE = 4;

// ----
const ADDRESSES_IN_BLOCK = BLOCK_SIZE / ADDRESS_SIZE;

export {
  DENTRY_SIZE,
  ADDRESS_SIZE,
  N_SIZE,
  BLOCK_SIZE,
  BLOCK_COUNT,
  DEVICE_SIZE,
  INODE_SIZE,
  INODE_INO_SIZE,
  INODE_TYPE_SIZE,
  INODE_SIZE_SIZE,
  INODE_REFS_SIZE,
  INODE_STRAIGHT_LINKS_COUNT,
  ADDRESSES_IN_BLOCK,
  MAX_SYMLINK_DEPTH,
};
